using System;
using System.Linq;

namespace DyeListGenerator
{
    public class Yarn
    {
        public double NumberOfSkeins { get; }
        public YarnType YarnType { get; }
        public String YarnTypeDescription { get; }

        public Color Color { get; }

        public bool IsMiniSkein
        {
            get { return YarnTypeDescription.Any(char.IsDigit); }
        }

        public Yarn(double numberOfSkeins, YarnType yarnType, String yarnTypeDescription)
        {
            NumberOfSkeins = numberOfSkeins;
            YarnType = yarnType;
            YarnTypeDescription = yarnTypeDescription;
        }

        public static Yarn CreateYarnFromText(string inputText)
        {
            //,5,BSK,Bobby BFL
            inputText = inputText.TrimStart(',');
            String[] inputs = inputText.Split(',');

            double quantity = double.Parse(inputs[0]);
            YarnType yarnType = YarnFactory.CreateYarnTypeFromText(inputs[1]);
            String yarnTypeDescription = inputs[2];

            (yarnType, quantity) = YarnFactory.ModifyValuesForMiniSkeins(yarnTypeDescription, quantity, yarnType);

            Yarn yarn = new Yarn(quantity, yarnType, yarnTypeDescription);

            return yarn;
        }
    }

    public enum YarnType
    {
        [YarnTypeProperties(5, MiniClassy)] Classy,

        [YarnTypeProperties(5, MiniClassyWCashmere)]
        ClassyWCashmere,
        [YarnTypeProperties(4, MiniSmooshy)] Smooshy,

        [YarnTypeProperties(4, MiniSmooshyWCashmere)]
        SmooshyWCashmere,
        [YarnTypeProperties(4, MiniJilly)] Jilly,

        [YarnTypeProperties(4, MiniJillyWCashmere)]
        JillyWCashmere,

        [YarnTypeProperties(4, MiniJillyLaceCashmere)]
        JillyLaceCashmere,
        [YarnTypeProperties(4, MiniCosette)] Cosette,
        [YarnTypeProperties(5, MiniCity)] City,
        Mohair,
        [YarnTypeProperties(4, MiniBFL2Ply)] BFL2Ply,
        [YarnTypeProperties(4, MiniBFLSock)] BFLSock,
        [YarnTypeProperties(4, MiniBFLDK)] BFLDK,
        MiniClassy,
        MiniClassyWCashmere,
        MiniSmooshy,
        MiniSmooshyWCashmere,
        MiniJilly,
        MiniJillyWCashmere,
        MiniJillyLaceCashmere,
        MiniCosette,
        MiniCity,
        MiniMohair,
        MiniBFL2Ply,
        MiniBFLSock,
        MiniBFLDK
    }

    public enum Color
    {
        NINETEENTH_DOTS,
        SIX_OF_EVERYTHING,
        A_LITTLE_NIGHT_MUSIC,
        ABSOLUTE_MAGENTA,
        AFTER_HOURS,
        ALIVE,
        ALL_AMERICAN_HEN,
        AMBER_GLASS,
        AMETHYST,
        AMETHYST_INK,
        ANGEL,
        ANGELICA,
        ANGELS_LANDING,
        ANYTHING_GOES,
        APATHY,
        AQUA_JET,
        AS_A_BIRD,
        ATOMIC_BLUE,
        AWESOME_WOW,
        AZURE_COVE,
        BASALT,
        BEDTIME,
        BELLE_EPOQUE,
        BELOW_HORIZON,
        BERMUDA_TEAL,
        BITTER,
        BITTER_MALAISE,
        BLACK_AND_WHITE,
        BLACK_PEARL,
        BLANCHEFLEUR_DOTS,
        BLUE_FISH,
        BLUE_LAGOON,
        BLUE_SAGE,
        BLUE_SULK,
        BOOT_CAMP,
        BRILLIANT,
        BROWNIE,
        BURR,
        CABARET,
        CALDERA,
        CALLOUS_PINK,
        CANDY_LOVE,
        CARMEN_MIRANDA,
        CAROLINA,
        CAROUSEL,
        CATCHING_STARS,
        CEDAR_CREEK,
        CHARCOAL_PRISMATIC,
        CHARGED_CHERRY,
        CHARLI_AU_LAIT,
        CHESLEY,
        CHILI,
        CHOCOLATE_NIGHT,
        CINNAMON_GIRL,
        CITIES_TOWERS_BRIDGES,
        CLOUD_TO_GROUND,
        CLOUDY,
        CONCORD,
        CONGO,
        CRANBERRY_MELT,
        CRISP,
        CRYING_DOVE,
        CRYSTAL_STORM,
        DAMP_PILLOW,
        DARK_CURRENT,
        DAYLILLY,
        DEEP_REGRET,
        DEEP_SEAFLOWER,
        DESERT_CITY_WATTAGE,
        DESERT_OASIS,
        DEVILS_GARDEN,
        DIVE,
        DIVINE,
        DO_RE_ME,
        DREAM_ON,
        DREAMGIRLS,
        DUNE,
        DUSK_TO_DAWN,
        EATEN_THE_PLUMS,
        EGGPLANT,
        ELECTRIC_MAUVE,
        ELEMENT_SEVENTY_NINE,
        ELIZA,
        ELYSIAN,
        EMERALD_DARKNESS,
        EVENING_FLAME,
        FABLE__DOTS,
        FANCY,
        FATAL_DUEL,
        FEDERAL_BANK,
        FERN_SLIPPER,
        FIERCE_SCARLET,
        FLOWER_DRUM_SONG,
        FORGET_ME,
        FORTUNE,
        FORTUNE_TELLER,
        GALAXY,
        GET_DOWN_GREENY,
        GG_LAUREL,
        GHOST_TOWN,
        GILT,
        GOBLIN_VALLEY,
        GOLD_EXPERIENCE,
        GOLD_MINE,
        GOOD_LUCK_JADE,
        GREEN_LANTERN,
        GREY_TABBY,
        GROW,
        GUTHRIE_PEAK,
        HAYWIRE,
        HEAR_IT_HAWAII,
        HEAVENLY,
        HELLO_DOLLY,
        HER_BEACON_HAND,
        HER_CHARISMA,
        HERBAL,
        HEY_SUNSHINE,
        HOLLY,
        HOT_AIR_BALLOON,
        HOT_PANTS,
        HUMDRUM,
        ICELAND,
        ICY_RECEPTION,
        INDIGO,
        ISLAND,
        ITS_A_SPARKLER,
        IVY_SNOWBELL_DOTS,
        JAY_FEATHER,
        JEANS,
        JESSAMYN,
        JOCELYN,
        JOSHUA_TREE,
        JULIETTES_BLUSH,
        JUST_TO_SAY,
        K_CHAMELEON,
        KISS_ME_KATE,
        KYOTO_SUNSET,
        LA_LUZ,
        LAFAYETTE,
        LAVENDER_BLOOM,
        LAY_A_ROSE,
        LEAF_SEED_BEAN,
        LEPRECHAUN_BALLET,
        LIBERATION,
        LIFE_OF_THE_GODS,
        LIPSTICK_LAVA,
        LITTLE_GREEN_MEN,
        LOOSE_GEMS,
        LOST_IN_PLUM,
        MAGIC_ORCHID,
        MALIBU_SAIL,
        MEDIEVAL,
        MELON_BOMB,
        MERCADO_LIGHTS,
        MERMAID_SHOES,
        MESA,
        MIAMI_RED,
        MILD_TEDIUM,
        MILKY_SPITE,
        MIST_OF_NYX,
        MOCCASIN,
        MOD_SQUAD,
        MORNING_GLORY,
        MY_FAIR_LADY,
        NAKED_SHAME,
        NAVY_ZEAL,
        NEBULA,
        NIGHTHAWKS,
        NO_LIMIT,
        NOVEMBER_MUSE,
        OLD_PUEBLO,
        OLD_VINE,
        OUT_BEYOND,
        PASSION,
        PEACEFUL_TRANSITION,
        PEACOCK_SHADOW,
        PENCHANT,
        PETAL_SHOWER,
        PETRIFIED_FOREST,
        PICKLE_BALL,
        PINK_BEAN,
        PINKY,
        PINOT,
        PLENTY,
        POMA_GRENADE,
        POPPY,
        POWER_PLANT,
        PRICKLY_PEAR,
        PRINCE_WILLIAM,
        PUNKY_FUCHSIA,
        PURPLE_RAIN,
        QUEENS_LAKE,
        RABBIT_EARS,
        RAIN_CLOUD,
        RAIN_ON_ME,
        RASPBERRY_BLAZE,
        RED_RUSH,
        REGENCY,
        RELISH_THE_VOTE,
        RETRIEVER,
        REYNOLDS,
        RING_THE_BLOSSOM_BELL,
        RIO_VERDE,
        RIOT_GIRLS,
        ROCHAMBEAU,
        ROMEO_BLUE,
        ROSALITA,
        ROSE_ANGUISH,
        ROSY,
        ROUTE_SIXTY_SIX,
        SANGRIA,
        SCORCHED_LIME,
        SECRET_GARDEN,
        SHADOW_BOX,
        SHE_WALKS_IN_BEAUTY,
        SHINY_MOSS,
        SHUYLER_LAKE,
        SHY,
        SIMONE_AND_SUSAN,
        SINGING_IN_THE_RAIN,
        SKIPPING_STONE,
        SKYROCKET,
        SLAMMIN_LEMON,
        SLIPPERY_TRAIL,
        SOLAR_GLITTER,
        SONORAN_SKY,
        SOUTH_PACIFIC,
        SPRING_TICKLE,
        SPROUT,
        STARLESS_SKY,
        STILL_I_RISE,
        STILL_SPRUCE,
        STRANGE_HARVEST,
        STRAW_INTO_GOLD,
        STRIKES_TWICE,
        STRING_AND_KEY__DOTS,
        SUNDOWN_ORCHID,
        SURF,
        TANG,
        TART,
        TEA_PARTY,
        TEX_MEX,
        THE_KING,
        TIDAL,
        TIDEWATER,
        TIFFANY_BOX,
        TIME_AWAY,
        TOKYO_CREAM,
        TORCHWOOD,
        TRANQUIL,
        TRUE_TO_LIFE,
        TUCSON,
        TUMBLEWEED,
        TUSSIE_MUSSIE,
        UNIMAGINABLE,
        UNIVERSE_IS_YOURS,
        UPTOWN_ELECTRIC,
        URBAN_FOSSIL,
        VAGUE_UNEASE,
        VALENTINE,
        VELVET_PORT,
        VICTORIA,
        VIOLETS_BLUEBERRY,
        VISUAL_PURPLE,
        VIVID,
        WATCH_MY_RISING,
        WAY_COOL_CRISTAL,
        WHETSTONE,
        WHIP_AND_CHILL,
        WHISPER_DOTS,
        WICKED_ROYAL,
        WILDERNESS,
        WINEBERRY,
        WORN_NICKEL,
    }
}